# Generated by Django 4.0.4 on 2022-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('turnover', models.CharField(max_length=100)),
                ('open', models.CharField(max_length=100)),
                ('high', models.CharField(max_length=100)),
                ('low', models.CharField(max_length=100)),
                ('close', models.CharField(max_length=100)),
                ('transactions', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
